### ISSUE TITLE
Using libjit for stack based VM

### ISSUE THREAD

**Issue by smaludzi** [eliben/libjit-samples#1]
Hi,

I would like to use libjit for stack based VM. Do you know how to change the following bytecode into jit-ed version using libjit?

Lets say we have the following function:

int test\_min(int a, int b) { return (a < b) ? a : b; }

Code:
0: iload_0
1: iload_1
2: if_icmpge     9
5: iload_0
6: goto          10
9: iload_1
10: ireturn

Do you know how to manage stack when the above bytecode is compiled using JIT? Without JIT reference to an object from the top of stack is returned. I would like to translate each bytecode into separate jit_insn function calls however cannot imagine how this can be done automatically.

I am attaching simple program where I commented hurdles.

[simple_jit.zip](https://github.com/eliben/libjit-samples/files/6802144/simple_jit.zip)

Thank you for help.
Sławomir Maludziński

**Comment by eliben** [comment]
Sorry, this is just a repository of samples provided to the public domain. I'm not the maintainer of libjit and I can't provide support for it.
